apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: call-scribe-database
  namespace: call-scribe
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: azurekv-cluster-secret-store
  target:
    name: call-scribe-database
    creationPolicy: Owner
    deletionPolicy: Retain
    template:
      engineVersion: v2
      type: kubernetes.io/basic-auth
      data:
        username: call_scribe
        password: "{{ .password }}"
        uri: "postgresql://call_scribe:{{ .password | urlquery }}@call-scribe-postgres-rw.call-scribe.svc.cluster.local:5432/call_scribe?sslmode=require"
  data:
    - secretKey: password
      remoteRef:
        key: secret/call-scribe-postgres-password
