apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "call-scribe.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-options: Prune=false,Delete=false
    helm.sh/resource-policy: keep
  labels:
    {{- include "call-scribe.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size | quote }}
  {{- with .Values.persistence.storageClassName }}
  storageClassName: {{ . | quote }}
  {{- end }}
